services:
  postgres:
    image: postgres:18
    container_name: sudocodes_pos_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sudocodes_pos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sudocodes_pos"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
